/**
 * Renders a CaseFile to two formats:
 *  - Markdown (for the lawyer to drop straight into the matter folder).
 *  - JSON (for archival / re-import).
 *
 * The Markdown layout follows the OVB Behandeling-dossier four-folder
 * convention so an Antwerp-bar partner can paste it into their existing
 * file structure with no reorganisation. Cover sheet, executive summary,
 * parties, conflict gate, chronology, issues + case theory, exhibits,
 * procedural posture, damages — in the order ABA Trial-Notebook readers
 * expect.
 */

import type { CaseFile, OvbFolder } from "./case-file-types";
import { SITE } from "@/lib/site";

const FOLDER_TITLE: Record<OvbFolder, string> = {
  "01_Intake": "01 — Intake",
  "02_Communicatie": "02 — Communicatie",
  "03_Processtukken": "03 — Processtukken",
  "04_Overige_stukken": "04 — Overige stukken",
};

function fmtEuro(minor: number | null | undefined): string {
  if (minor === null || minor === undefined) return "—";
  return `€ ${(minor / 100).toLocaleString("en-BE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function fmtDate(iso?: string, fallback?: string): string {
  if (iso) return iso;
  if (fallback) return fallback;
  return "—";
}

function srcLabel(ref: { kind: string; ref: string; quote?: string }): string {
  const base = ref.kind === "document" ? `Doc: ${ref.ref}` : ref.kind === "user_message" ? `Msg #${ref.ref}` : `NEO #${ref.ref}`;
  return ref.quote ? `${base} — "${ref.quote}"` : base;
}

// ---------------------------------------------------------------------------
// Markdown export — single self-contained document.
// ---------------------------------------------------------------------------

export function caseFileToMarkdown(cf: CaseFile): string {
  const out: string[] = [];

  // ----- Cover -----
  out.push(`# Case File — ${cf.cover.caption}`);
  out.push("");
  out.push(`> Generated by NEO for ${SITE.shortName} on ${new Date(cf.cover.openedAt).toISOString().slice(0, 10)}.`);
  out.push(`> Matter id: \`${cf.cover.matterId}\` · Status: \`${cf.cover.status}\` · Language: ${cf.cover.language}`);
  out.push("");
  out.push("| Field | Value |");
  out.push("| --- | --- |");
  out.push(`| Practice area | ${cf.cover.practiceArea} |`);
  out.push(`| Urgency | **${cf.cover.urgency}** |`);
  out.push(`| Suggested lead | ${cf.cover.suggestedLead ?? "—"} |`);
  out.push(`| Next deadline | ${cf.cover.nextDeadline ?? "—"} |`);
  out.push(`| Statute-of-limitations alert | ${cf.cover.statuteOfLimitationsAlert ?? "—"} |`);
  out.push("");
  out.push(`**Theme.** ${cf.cover.theme}`);
  out.push("");

  // ----- Executive summary -----
  out.push("## Executive summary");
  out.push("");
  out.push(cf.executiveSummary.paragraph);
  out.push("");
  for (const b of cf.executiveSummary.bullets) out.push(`- ${b}`);
  out.push("");

  // ----- Risk gate (always near the top — non-negotiable per ABA Rule 1.7 / OVB) -----
  out.push("## Risk & conflict gate");
  out.push("");
  if (cf.risk.conflictFlags.length === 0 && !cf.risk.sensitiveMatter && !cf.risk.jurisdictionRisk && !cf.risk.concurrentCounselMentioned) {
    out.push("_No automatic risk signal raised by intake. The lawyer's formal conflict check is still required._");
  } else {
    if (cf.risk.conflictFlags.length > 0) {
      out.push("**Soft conflict signals (lawyer review required):**");
      for (const f of cf.risk.conflictFlags) out.push(`- \`${f.severity}\` ${f.label} — ${f.reason}`);
      out.push("");
    }
    if (cf.risk.sensitiveMatter) out.push("- Sensitive subject-matter cue detected → apply firm's sensitive-matter protocol.");
    if (cf.risk.jurisdictionRisk) out.push("- Possible out-of-jurisdiction matter → confirm Belgian competence.");
    if (cf.risk.concurrentCounselMentioned) out.push("- Visitor mentioned existing counsel → verify no double representation.");
    out.push("");
  }
  out.push("**Pre-engagement checks:**");
  for (const c of cf.risk.preEngagementChecks) out.push(`- [ ] ${c}`);
  out.push("");

  // ----- Parties -----
  out.push("## Parties");
  out.push("");
  if (cf.parties.length === 0) {
    out.push("_No parties extracted yet._");
  } else {
    out.push("| Role | Name | Kind | Relationship | Source |");
    out.push("| --- | --- | --- | --- | --- |");
    for (const p of cf.parties) {
      out.push(`| ${p.role} | ${p.name} | ${p.kind} | ${p.relationship ?? "—"} | ${srcLabel(p.source)} |`);
    }
  }
  out.push("");

  // ----- Chronology -----
  out.push("## Chronology");
  out.push("");
  if (cf.chronology.length === 0) {
    out.push("_No timeline events extracted yet._");
  } else {
    out.push("| # | Date (parsed) | Date (verbatim) | Event | Source |");
    out.push("| --- | --- | --- | --- | --- |");
    cf.chronology.forEach((c, i) => {
      out.push(`| ${i + 1} | ${fmtDate(c.dateIso)} | ${c.dateText} | ${c.event} | ${srcLabel(c.source)} |`);
    });
  }
  out.push("");

  // ----- Issues + theory -----
  out.push("## Legal issues");
  out.push("");
  if (cf.issues.length === 0) {
    out.push("_No issues inferred yet._");
  } else {
    cf.issues.forEach((iss, i) => {
      out.push(`### Issue ${i + 1}: ${iss.question}`);
      out.push(`- **Area:** ${iss.area}`);
      out.push(`- **Strength (intake estimate):** ${iss.strength}`);
      if (iss.remedySought) out.push(`- **Remedy sought:** ${iss.remedySought}`);
      if (iss.openQuestions.length > 0) {
        out.push(`- **Open questions:**`);
        for (const q of iss.openQuestions) out.push(`  - ${q}`);
      }
      out.push("");
    });
  }

  out.push("### Case theory (NITA framework — intake hypothesis only)");
  out.push("");
  out.push(`- **Legal theory.** ${cf.caseTheory.legalTheory}`);
  out.push(`- **Factual theory.** ${cf.caseTheory.factualTheory}`);
  out.push(`- **Persuasive theory.** ${cf.caseTheory.persuasiveTheory}`);
  out.push("");

  // ----- Exhibits -----
  out.push("## Evidence index");
  out.push("");
  if (cf.exhibits.length === 0) {
    out.push("_No documents attached._");
  } else {
    out.push("| Ref | Filename | Class | Description | Status |");
    out.push("| --- | --- | --- | --- | --- |");
    for (const e of cf.exhibits) {
      out.push(`| ${e.ref} | ${e.filename} | ${e.classification} | ${e.oneLiner} | ${e.uploadStatus} |`);
    }
  }
  out.push("");

  // ----- Procedural posture -----
  out.push("## Procedural posture & deadlines");
  out.push("");
  if (cf.procedural.length === 0) {
    out.push("_No deadlines or procedural events extracted._");
  } else {
    out.push("| Date | Verbatim | Kind | Hard stop | Description | Source |");
    out.push("| --- | --- | --- | --- | --- | --- |");
    for (const p of cf.procedural) {
      out.push(`| ${fmtDate(p.dateIso)} | ${p.dateText} | ${p.kind} | ${p.isHardStop ? "YES" : "no"} | ${p.description} | ${srcLabel(p.source)} |`);
    }
  }
  out.push("");

  // ----- Damages -----
  out.push("## Damages / quantum");
  out.push("");
  if (cf.damages.entries.length === 0) {
    out.push("_No monetary stakes mentioned._");
  } else {
    out.push("| Category | Amount (verbatim) | Amount (parsed) | Description | Source |");
    out.push("| --- | --- | --- | --- | --- |");
    for (const d of cf.damages.entries) {
      out.push(`| ${d.category} | ${d.amountText} | ${fmtEuro(d.amountEurMinor)} | ${d.description} | ${srcLabel(d.source)} |`);
    }
    out.push("");
    out.push(`**Estimated total (intake-side, lawyer to validate):** ${fmtEuro(cf.damages.totalEurMinor)}`);
  }
  out.push("");

  // ----- Open questions for the lawyer -----
  out.push("## Open questions for the lawyer");
  out.push("");
  for (const q of cf.openQuestionsForLawyer) out.push(`- [ ] ${q}`);
  out.push("");

  // ----- OVB allocation map -----
  out.push("## Belgian dossier allocation (OVB Behandeling-dossier indeling)");
  out.push("");
  const byFolder: Record<OvbFolder, { label: string; rationale: string }[]> = {
    "01_Intake": [],
    "02_Communicatie": [],
    "03_Processtukken": [],
    "04_Overige_stukken": [],
  };
  for (const a of cf.ovbAllocation) byFolder[a.folder].push({ label: a.label, rationale: a.rationale });
  for (const folder of Object.keys(byFolder) as OvbFolder[]) {
    const items = byFolder[folder];
    if (items.length === 0) continue;
    out.push(`### ${FOLDER_TITLE[folder]}`);
    for (const it of items) out.push(`- **${it.label}** — ${it.rationale}`);
    out.push("");
  }

  // ----- Transcript -----
  out.push("## Conversation transcript (verbatim)");
  out.push("");
  cf.transcript.forEach((t, i) => {
    const tag = t.role === "user" ? "VISITOR" : "NEO";
    const via = t.via === "voice" ? " · dictated" : "";
    out.push(`**[${i + 1}] ${tag}${via} · ${t.ts}**`);
    out.push("");
    out.push(t.text);
    out.push("");
  });

  out.push("---");
  out.push("");
  out.push(
    `_${SITE.disclaimer} — This case file was assembled by NEO from the visitor's own messages. Every fact carries a source pointer (Msg # or Doc:) so the lawyer can verify in seconds._`,
  );
  return out.join("\n");
}

// ---------------------------------------------------------------------------
// JSON export
// ---------------------------------------------------------------------------

export function caseFileToJson(cf: CaseFile): string {
  return JSON.stringify(cf, null, 2);
}

// ---------------------------------------------------------------------------
// Browser helpers — copy / download.
// ---------------------------------------------------------------------------

export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof navigator === "undefined" || !navigator.clipboard) return false;
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function downloadFile(filename: string, content: string, mime: string): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function caseFileFilename(cf: CaseFile, ext: "md" | "json" | "pdf" | "docx"): string {
  const safe = cf.cover.caption
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  const date = new Date(cf.cover.openedAt).toISOString().slice(0, 10);
  return `case-file_${date}_${safe || cf.cover.matterId}.${ext}`;
}
